<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>constraint_vel_controller</name>
  <version>1.0.0</version>
  <description>Nav2 controller wrapper for applying velocity and motion constraints.</description>
  <maintainer email="1834364183@qq.com">xx</maintainer>
  <maintainer email="qza36@outlook.com">ZhiangQi</maintainer>
  <license>MIT</license>
  <author email="1834364183@qq.com">xx</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>nav2_core</depend>
  <depend>nav2_util</depend>
  <depend>nav2_costmap_2d</depend>
  <depend>pluginlib</depend>
  <depend>tf2_ros</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
